(function(){
'use strict';
const profile=window.__BROWSER_PROFILE==='safari'?'SAFARI':'CHROME';
const scene=new THREE.Scene();scene.background=new THREE.Color(0xb9d7da);scene.fog=new THREE.Fog(0xb9d7da,90,245);
const camera=new THREE.PerspectiveCamera(50,innerWidth/innerHeight,.1,420);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,profile==='SAFARI'?1.0:1.2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.appendChild(renderer.domElement);
const RAMPS=[['#3d584c','#8fa86a'],['#66727a','#ece5d6'],['#4f302d','#b26a52'],['#3a312c','#82644e'],['#33444d','#aababc'],['#30433b','#d7c58e'],['#2b4550','#6d969e'],['#6b453b','#c77b61'],['#30363b','#727a82'],['#5f4037','#cc987c']];
const lc=document.createElement('canvas');lc.width=256;lc.height=RAMPS.length;const ctx=lc.getContext('2d');RAMPS.forEach((r,i)=>{ctx.fillStyle=r[0];ctx.fillRect(0,i,88,1);ctx.fillStyle=r[1];ctx.fillRect(88,i,168,1)});const lut=new THREE.CanvasTexture(lc);lut.magFilter=lut.minFilter=THREE.NearestFilter;lut.generateMipmaps=false;lut.colorSpace=THREE.SRGBColorSpace;
const SUN=new THREE.Vector3(-.55,.78,.34).normalize();
function makeMat(row){return new THREE.ShaderMaterial({uniforms:{uLut:{value:lut},uRows:{value:RAMPS.length},uRow:{value:row},uSun:{value:SUN}},vertexShader:'varying vec3 vN;void main(){vN=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform sampler2D uLut;uniform float uRows,uRow;uniform vec3 uSun;varying vec3 vN;void main(){float d=dot(normalize(vN),normalize(uSun))*.5+.5;float amb=.13+.16*max(vN.y,0.0);float u=clamp(d*.84+amb,0.,1.);gl_FragColor=texture2D(uLut,vec2(u,(uRow+.5)/uRows));}',flatShading:true});}
const M={grass:makeMat(0),concrete:makeMat(1),brick:makeMat(2),wood:makeMat(3),stone:makeMat(4),accent:makeMat(5),glass:makeMat(6),terracotta:makeMat(7),metal:makeMat(8),skin:makeMat(9)};
function box(parent,s,p,m,r=0){const x=new THREE.Mesh(new THREE.BoxGeometry(s[0],s[1],s[2]),m);x.position.set(p[0],p[1],p[2]);x.rotation.y=r;parent.add(x);return x}
function cyl(parent,r,h,p,m,n=8){const x=new THREE.Mesh(new THREE.CylinderGeometry(r,r*1.03,h,n),m);x.position.set(p[0],p[1],p[2]);parent.add(x);return x}
function roof(parent,w,d,y,m){const g=new THREE.ConeGeometry(Math.max(w,d)*.62,.8,4);g.scale(w/Math.max(w,d),1,d/Math.max(w,d));g.rotation.y=Math.PI/4;const x=new THREE.Mesh(g,m);x.position.y=y;parent.add(x);return x}
const world=new THREE.Group();scene.add(world);box(world,[260,.1,260],[0,-.05,0],M.grass);
const roads=new THREE.Group();world.add(roads);const GX=[-96,-64,-32,0,32,64,96],GZ=[-64,-32,0,32,64];for(const x of GX)box(roads,[7,.08,205],[x,.01,0],M.concrete);for(const z of GZ)box(roads,[205,.08,7],[0,.01,z],M.concrete);for(const x of [-80,-48,-16,16,48,80])box(roads,[2.4,.045,25],[x,.07,-16],M.metal);for(const z of [-48,-16,16,48])box(roads,[25,.045,2.4],[-16,.07,z],M.metal);
const river=new THREE.Group();world.add(river);box(river,[205,.1,26],[0,-.03,91],M.glass);for(let x=-90;x<=90;x+=18){box(river,[15,.05,.55],[x,.05,78+Math.sin(x*.1)],M.stone);box(river,[15,.05,.55],[x,.05,104+Math.cos(x*.11)],M.stone)}box(river,[17,.45,28],[0,.25,79],M.wood);for(const sx of [-6.5,6.5])for(let i=-3;i<=3;i++)cyl(river,.42,1.4,[sx,.9,79+i*4.2],M.stone,7);
const buildings=new THREE.Group();world.add(buildings);const bdata=[];let seed=1;function rnd(){const v=Math.sin(seed++*91.173)*43758.5453;return v-Math.floor(v)}
function building(x,z,w,d,h,style){const g=new THREE.Group();g.position.set(x,0,z);const base=style===0?M.concrete:style===1?M.brick:M.stone;box(g,[w,h,d],[0,h/2,0],base);const pod=Math.min(4,h*.22);box(g,[w*1.06,pod,d*1.04],[0,pod/2,0],style===1?M.brick:M.concrete);if(h<18)roof(g,w,d,h+.3,style===1?M.terracotta:M.metal);else box(g,[w*.68,.5,d*.68],[0,h+.25,0],M.metal);for(const yy of [3,6,9,12,15,18,21,24])if(yy<h-.8){box(g,[w*.72,.055,.05],[0,yy,d/2+.025],M.accent);box(g,[w*.72,.055,.05],[0,yy,-d/2-.025],M.accent)}buildings.add(g);bdata.push({g,x,z,w,d,h})}
for(const x of [-112,-80,-48,-16,16,48,80,112])for(const z of [-80,-48,-16,16,48,112]){if(Math.abs(x)<34&&Math.abs(z-91)<26)continue;const r=rnd(),h=8+r*24;building(x,z,13+r*6,13+(1-r)*6,h,Math.floor(r*3))}
const landmarks=new THREE.Group();world.add(landmarks);
function fed(){const g=new THREE.Group();g.position.set(-18,0,28);for(const p of [[-10,3,6],[9,4,5],[-6,2,-5],[8,5,-7]]){const h=p[1]+6;const q=box(g,[11,h,8],[p[0],h/2,p[2]],M.concrete,p[0]*.02);q.rotation.z=p[0]>.0?.03:-.025}box(g,[29,.3,21],[0,.16,1],M.stone);return g}landmarks.add(fed());
function flinders(){const g=new THREE.Group();g.position.set(16,0,30);box(g,[39,8,12],[0,4,0],M.brick);box(g,[17,11,10],[0,5.2,0],M.brick);cyl(g,4.2,1,[0,8.5,0],M.terracotta,14);for(const sx of [-13,13])cyl(g,2.1,6,[sx,5.2,0],M.terracotta,12);for(let i=-6;i<=6;i++)box(g,[1.4,3,.18],[i*2.8,3,6.1],M.accent);return g}landmarks.add(flinders());
function eureka(){const g=new THREE.Group();g.position.set(61,0,29);box(g,[10,43,10],[0,21.5,0],M.glass);box(g,[13,3,13],[0,43.2,0],M.metal);box(g,[5,9,5],[0,49,0],M.accent);return g}landmarks.add(eureka());
function arts(){const g=new THREE.Group();g.position.set(44,0,61);box(g,[19,6,15],[0,3,0],M.stone);cyl(g,1.4,28,[0,19,0],M.metal,10);box(g,[7,4,7],[0,8,0],M.terracotta);return g}landmarks.add(arts());
function qvm(){const g=new THREE.Group();g.position.set(-61,0,-58);box(g,[35,6,17],[0,3,0],M.brick);roof(g,35,17,6.4,M.terracotta);for(let i=-2;i<=2;i++)box(g,[.9,3.5,.18],[i*6,2.1,8.6],M.accent);return g}landmarks.add(qvm());
const trees=new THREE.Group();world.add(trees);const dummy=new THREE.Object3D();const tg=new THREE.CylinderGeometry(.16,.19,2,7),cg=new THREE.IcosahedronGeometry(.86,1),tm=new THREE.InstancedMesh(tg,M.wood,64),cm=new THREE.InstancedMesh(cg,M.grass,64);let ti=0;for(let x=-112;x<=112&&ti<64;x+=16)for(const z of [-54,-22,10,54]){dummy.position.set(x,.98,z);dummy.rotation.z=(ti%2?-.05:.05);dummy.scale.setScalar(.9+((ti*13)%9)/50);dummy.updateMatrix();tm.setMatrixAt(ti,dummy.matrix);dummy.position.y=2.25;dummy.updateMatrix();cm.setMatrixAt(ti,dummy.matrix);ti++}tm.instanceMatrix.needsUpdate=true;cm.instanceMatrix.needsUpdate=true;trees.add(tm,cm);
const win=new THREE.InstancedMesh(new THREE.BoxGeometry(.85,.62,.05),M.glass,900);let wi=0;for(const b of bdata){const rows=Math.min(9,Math.floor((b.h-2)/2.3)),cols=Math.min(8,Math.floor(b.w/1.8));for(let r=0;r<rows&&wi<900;r++)for(let c=0;c<cols&&wi<900;c++){dummy.position.set(b.x-b.w*.5+1.2+c*1.75,1.55+r*2.3,b.z+b.d*.5+.03);dummy.rotation.set(0,0,0);dummy.scale.set(1,1,1);dummy.updateMatrix();win.setMatrixAt(wi++,dummy.matrix)}}win.instanceMatrix.needsUpdate=true;world.add(win);
const player=new THREE.Group();player.position.set(-52,.08,-18);world.add(player);box(player,[.5,1.5,.44],[0,.78,0],M.metal);box(player,[1.15,1,.64],[0,1.67,0],M.wood);box(player,[.72,.38,.68],[0,2.2,.02],M.concrete);const head=new THREE.Mesh(new THREE.IcosahedronGeometry(.36,1),M.skin);head.position.y=3;player.add(head);const hair=new THREE.Mesh(new THREE.IcosahedronGeometry(.31,1),M.metal);hair.scale.y=.55;hair.position.y=3.25;player.add(hair);
const keys=new Set();let yaw=.72,pitch=.31,distance=10.7,drag=false,lastX=0,lastY=0;addEventListener('keydown',e=>{keys.add(e.code);if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'){drag=true;lastX=e.clientX;lastY=e.clientY}});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-lastX)*.005;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-lastY)*.003,.1,.62);lastX=e.clientX;lastY=e.clientY});addEventListener('wheel',e=>distance=THREE.MathUtils.clamp(distance+e.deltaY*.012,7.5,15.5),{passive:true});
function move(dt){let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);let z=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);const len=Math.hypot(x,z);if(!len)return;x/=len;z/=len;const c=Math.cos(yaw),s=Math.sin(yaw);const dx=(x*c-z*s)*4.2*dt,dz=(x*s+z*c)*4.2*dt;player.position.x=THREE.MathUtils.clamp(player.position.x+dx,-122,122);player.position.z=THREE.MathUtils.clamp(player.position.z+dz,-122,122);player.rotation.y=Math.atan2(dx,dz)}
function cameraFollow(dt){const target=new THREE.Vector3(player.position.x,player.position.y+1.75,player.position.z);const cp=Math.cos(pitch),sp=Math.sin(pitch);const desired=target.clone().add(new THREE.Vector3(Math.sin(yaw)*cp*distance,sp*distance,Math.cos(yaw)*cp*distance));camera.position.lerp(desired,1-Math.pow(.001,dt));camera.lookAt(target)}
const status=document.getElementById('status');document.getElementById('loading')?.remove();let prev=performance.now();function loop(){requestAnimationFrame(loop);const now=performance.now();const dt=Math.min((now-prev)/1000,.033);prev=now;move(dt);cameraFollow(dt);status.textContent=profile+' · Melbourne CBD · FPS '+Math.round(1/Math.max(dt,.001))+' · CALLS '+renderer.info.render.calls;renderer.render(scene,camera)}camera.position.set(10,6,12);camera.lookAt(player.position.x,1.5,player.position.z);loop();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
})();